// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPaths(arg1) {
  return window['go']['main']['App']['LoadPaths'](arg1);
}

export function Validate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Validate'](arg1, arg2, arg3);
}
