name: "Build and Test"
on:
  push:
    branches:
  pull_request:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Get Wails dependencies
        run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Wails doctor
        run: wails doctor
      - name: Build package linux
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          echo ${{ env.GITHUB_REF }}
          echo ${{ env.GITHUB_HEAD_REF }}
          mkdir -p ~/.wails
          cp wails.json ~/.wails/
          export LOG_LEVEL=debug
          export GODEBUG=1
          wails build -noPackage
      - name: Testing
        run: go test .
